#!/bin/bash

test $# -eq 1 && device="$1"

lol=${device##*/}

test ! -e /mnt/$lol && sudo mkdir /mnt/$lol

{ sudo cryptsetup luksOpen /dev/$device $lol && sudo mount /dev/mapper/$lol /mnt/$lol; } 2>/dev/null || sudo mount /dev/$device /mnt/$lol && echo "[eo] mounted at /mnt/$lol"
