#!/bin/bash

options="exit i3\npoweroff\nreboot\ncancel"
response=$(echo -e "$options" | rofi -dmenu -p "Select an option:" -font 'mono 18' -theme glue_pro_blue)

case "$response" in
    "exit i3")
        i3-msg exit
        ;;
    "poweroff")
        shutdown now
        ;;
    "reboot")
        reboot
        ;;
    "cancel")
        ;;
esac
