#!/bin/bash

generate_random_string() {
    local length=$1
    # head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c "$length"; echo
    openssl rand -base64 $length
}

generate_random_word() {
    local length=$1
    local word
    while true; do
        word=$(shuf -n 1 /usr/share/dict/british-english | tr -d '\n' | cut -c 1-"$length")
        [[ $word != *\'s ]] && break
    done
    echo "$word"
}

words=$(for length in {10..20}; do generate_random_word "$length"; done)
strings="---------"

for ((length = 3; length <= 18; length += 3)); do
    random_string=$(generate_random_string "$length")
    strings+="\n$random_string"
done

if [[ "${strings: -1}" == $'\n' ]]; then
    strings="${strings%$'\n'}"
fi

echo -e "$words\n$strings" | rofi -dmenu -font "mono 18" -theme glue_pro_blue | xclip -selection clipboard
