#!/bin/bash

query=$(rofi -dmenu -i -p "Google search" -font 'Tamzen 15' -theme Monokai -show-icons -lines 0 -no-fixed-num-lines)

if [ -n "$query" ]; then
    waterfox "https://www.google.es/search?q=$query" &
fi
