#!/bin/bash

d=$(date -R)
if [ -d "$HOME/Recordings/screenshot-recordings$d" ]; then
    echo "The folder exists."
else
    mkdir "$HOME/Recordings/screenshot-recordings$d"
fi

counter=1
folder="$HOME/Recordings/screenshot-recordings$d"

while true; do
    filename="$folder/screenshot_$counter.png"

    scrot -pzq 1 -Z 9 "$filename"

    time avifenc "$filename" -o "$folder/screenshot_$counter.avif" 
    
    rm "$filename"

    ((counter++))
    
done
