#!/bin/bash

d=$(date -R)
if [ -d "$HOME/Recordings/screenshot-recordings$d" ]; then
    echo "The folder exists."
else
    mkdir "$HOME/Recordings/screenshot-recordings$d"
fi

counter=1
folder="$HOME/Recordings/screenshot-recordings$d"

while true; do
    filename="$folder/screenshot_$counter.png"

    scrot -pzq 1 -Z 9 "$filename"

    # cwebp -q 70 "$filename" -o "$folder/screenshot_$counter.webp"
    avifenc -q 70 "$filename" -o "$folder/screenshot_$counter.avif"
    
    rm "$filename"

    ((counter++))

    sleep 5
done
