#!/bin/bash

current_day=$(date +"%-e")

cal_output=$(cal | sed -E "s/\b$current_day\b/$current_day*/" | sed 's/^/    /')

rofi -font 'mono 18' -theme glue_pro_blue -e "
$cal_output
$(cowsay $(date +"%a, %d %b %Y %T %Z"))"

