#!/usr/bin/env fish

set options "chatgpt
bing ai
gmail
twitter
twitch
youtube
wikipedia
wiktionary
dle rae
oxford dictionary
pinterest
reddit
instagram
mastodon
4chan.org/g/
123movies"

set selected (echo $options | rofi -dmenu -font "Terminus 19" -theme Monokai)

switch $selected
    case "chatgpt"
        waterfox "https://chat.openai.com/chat/"
        ;;
    case "bing ai"
        waterfox "https://www.bing.com/search?q=Bing+AI&showconv=1&FORM=hpcodx/"
        ;;
    case "gmail"
        waterfox "https://gmail.com/"
        ;;
    case "twitter"
        waterfox "https://twitter.com/"
        ;;
    case "twitch"
        waterfox "https://www.twitch.tv/"
        ;;
    case "youtube"
        waterfox "https://www.youtube.com/"
        ;;
    case "wikipedia"
        waterfox "https://en.wikipedia.org/"
        ;;
    case "wiktionary"
        waterfox "https://es.wiktionary.org/"
        ;;
    case "oxford dictionary"
        waterfox "https://www.oxfordlearnersdictionaries.com/"
        ;;
    case "dle rae"
        waterfox "https://dle.rae.es/diccionario/"
        ;;
    case "pinterest"
        waterfox "https://www.pinterest.com/"
        ;;
    case "reddit"
        waterfox "https://www.reddit.com/"
        ;;
    case "instagram"
        waterfox "https://www.instagram.com/"
        ;;
    case "mastodon"
        waterfox "https://joinmastodon.org/"
        ;;
    case "4chan.org/g/"
        waterfox "https://4chan.org/g/catalog"
        ;;
    case "123movies"
        waterfox "https://ww2.123moviesfree.net/"
        ;;
    case "*"
        # Handle unexpected input
        ;;
end
