#!/bin/bash

echo -n "$(tr -dc "a-z" </dev/urandom | head -c 10)" > /tmp/r && \
where="xclip-$(cat /tmp/r)" && \

if [ "$(pwd)" != "$HOME" ]; then
	(xclip -selection clipboard -t image/png -o > $where.png && \
	cjxl -e 9 --lossless_jpeg=1 $where.png $where.jxl && rm $where.png || echo "error saving pic") > /dev/null 2>&1 &
else
	(xclip -selection clipboard -t image/png -o > ~/Desktop/$where.png && \
	cjxl -e 9 --lossless_jpeg=1 ~/Desktop/$where.png ~/Desktop/$where.jxl && rm ~/Desktop/$where.png || notify-send "error saving pic") > /dev/null 2>&1 &
fi
