#!/bin/bash

echo -n "$(tr -dc "a-z" </dev/urandom | head -c 10)" > /tmp/r && \
where="xclip-$(cat /tmp/r)" && \
(
  xclip -selection clipboard -t image/jpeg -o > "$( [ "$(pwd)" != "$HOME" ] && echo "$where.jpeg" || echo "~/Desktop/$where.jpeg" )" && \
  cjxl -e 9 --lossless_jpeg=1 "$( [ "$(pwd)" != "$HOME" ] && echo "$where.jpeg" || echo "~/Desktop/$where.jpeg" )" \
  "$( [ "$(pwd)" != "$HOME" ] && echo "$where.jxl" || echo "~/Desktop/$where.jxl" )" && \
  rm "$( [ "$(pwd)" != "$HOME" ] && echo "$where.jpeg" || echo "~/Desktop/$where.jpeg" )" || \
  ( [ "$(pwd)" != "$HOME" ] && echo "error saving pic" || notify-send "error saving pic" )
) > /dev/null 2>&1 &

